### ISSUE TITLE
can't plot

### ISSUE THREAD

**Issue by tegger2000** [AdrianVollmer/speedypy#1]
Hi, I can't plot, I got the following error:

X@LXCNAME:~$ ./.local/bin/speedypy plot time_series
Traceback (most recent call last):
  File "/home/admin/./.local/bin/speedypy", line 8, in <module>
    sys.exit(main())
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/__main__.py", line 6, in main
    args.func(args)
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/subcommands/plot.py", line 77, in time_series
    data = get_data(exclude_servers)
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/common.py", line 18, in get_data
    if int(j['server']['id']) not in exclude_servers:
TypeError: argument of type 'NoneType' is not iterable

**Comment by AdrianVollmer** [comment]
Thanks for reporting.

That's strange. What does your log file look like? Is there any content yet?

It's location should be in `~/.local/share/speedypy/speedtests.log`

I'll push a change that should make the error clearer. Please reinstall and try again.

**Comment by tegger2000** [comment]
[speetests.log](https://github.com/AdrianVollmer/speedypy/files/8325768/speetests.log)
looks good to me

**Comment by tegger2000** [comment]
X@LXCNAME:~/$ python3.10 -m pip install --user git+https://github.com/AdrianVollmer/speedypy
Collecting git+https://github.com/AdrianVollmer/speedypy
  Cloning https://github.com/AdrianVollmer/speedypy to /tmp/pip-req-build-o_4xba8v
  Running command git clone --filter=blob:none --quiet https://github.com/AdrianVollmer/speedypy /tmp/pip-req-build-o_4xba8v
  Resolved https://github.com/AdrianVollmer/speedypy to commit 1bc979a80e04d8120fdcaa3bcba7ef27013b8734
  Preparing metadata (setup.py) ... done
Requirement already satisfied: speedtest-cli in /home/X/.local/lib/python3.10/site-packages (from speedypy==0.0.1) (2.1.3)
Requirement already satisfied: matplotlib in /home/X/.local/lib/python3.10/site-packages (from speedypy==0.0.1) (3.5.1)
Requirement already satisfied: pandas in /home/X/.local/lib/python3.10/site-packages (from speedypy==0.0.1) (1.4.1)
Requirement already satisfied: pyxdg in /home/X/.local/lib/python3.10/site-packages (from speedypy==0.0.1) (0.27)
Requirement already satisfied: pillow>=6.2.0 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (1.4.0)
Requirement already satisfied: numpy>=1.17 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (1.22.3)
Requirement already satisfied: fonttools>=4.22.0 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (4.31.1)
Requirement already satisfied: packaging>=20.0 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (21.3)
Requirement already satisfied: cycler>=0.10 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /home/X/.local/lib/python3.10/site-packages (from matplotlib->speedypy==0.0.1) (3.0.7)
Requirement already satisfied: pytz>=2020.1 in /home/X/.local/lib/python3.10/site-packages (from pandas->speedypy==0.0.1) (2022.1)
Requirement already satisfied: six>=1.5 in /home/X/.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->speedypy==0.0.1) (1.16.0)

i tried the new version, but the error is still the same 

X@LXCNAME:~$ ./.local/bin/speedypy plot time_series
Traceback (most recent call last):
  File "/home/X/./.local/bin/speedypy", line 8, in <module>
    sys.exit(main())
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/__main__.py", line 6, in main
    args.func(args)
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/subcommands/plot.py", line 77, in time_series
    data = get_data(exclude_servers)
  File "/home/X/.local/lib/python3.10/site-packages/speedypy/common.py", line 18, in get_data
    if int(j['server']['id']) not in exclude_servers:
TypeError: argument of type 'NoneType' is not iterable

**Comment by AdrianVollmer** [comment]
Ah, I think the mistake was somewhere else. Pushed the fix, hopefully.

 And I think you're still running the old version. You can `rm -rf ~/.local/lib/python3.10/site-packages/speedypy` to make sure the old version is gone before re-installing.

The log file is fine and plots fine on my end.

**Comment by tegger2000** [comment]
with rm you need to use --force-reinstall, otherwise its not installed any more
X@LXCNAME:~$ ./.local/bin/speedypy --log-level ERROR measure
Traceback (most recent call last):
  File "/home/X/./.local/bin/speedypy", line 5, in <module>
    from speedypy.__main__ import main
ModuleNotFoundError: No module named 'speedypy'


where is the plot saved ?

**Comment by AdrianVollmer** [comment]
Oh, it just opens a window if you have Xorg running. If you  are on an SSH session, you could try `ssh -X ...`.

I never needed it in a file, put I just implemented that feature ;) reinstall and you can specify a file with `speedypy plot -o output.png time_series`.

**Comment by tegger2000** [comment]
-o xxx.png is working 👍 

with VNC on Xfce i got:

./.local/bin/speedypy plot time_series
/home/X/.local/lib/python3.10/site-packages/speedypy/subcommands/plot.py:117: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
